<?php
return [
  [
    'name' => 'SavedSearch_Presentation_Detail',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Presentation_Detail',
        'label' => 'Presentation Detail',
        'form_values' => NULL,
        'mapping_id' => NULL,
        'search_custom_id' => NULL,
        'api_entity' => 'Presentation',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'GROUP_CONCAT(DISTINCT Presentation_PresentationAuthor_Contact_01.display_name) AS GROUP_CONCAT_Presentation_PresentationAuthor_Contact_01_display_name',
            'GROUP_CONCAT(DISTINCT Presentation_PresentationAuthor_Contact_01.job_title) AS GROUP_CONCAT_Presentation_PresentationAuthor_Contact_01_job_title',
            'GROUP_CONCAT(Presentation_PresentationAuthor_Contact_01_Contact_Email_contact_id_01.email) AS GROUP_CONCAT_Presentation_PresentationAuthor_Contact_01_Contact_Email_contact_id_01_email',
            'topic_id:label',
            'title',
            'date',
            'audience_id:label',
            'type_id:label',
            'duration',
            'notes',
            'Presentation_custom.Presentation_file',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [
            'id',
          ],
          'join' => [
            [
              'Contact AS Presentation_PresentationAuthor_Contact_01',
              'LEFT',
              'PresentationAuthor',
              [
                'id',
                '=',
                'Presentation_PresentationAuthor_Contact_01.presentation_id',
              ],
            ],
            [
              'Email AS Presentation_PresentationAuthor_Contact_01_Contact_Email_contact_id_01',
              'LEFT',
              [
                'Presentation_PresentationAuthor_Contact_01.id',
                '=',
                'Presentation_PresentationAuthor_Contact_01_Contact_Email_contact_id_01.contact_id',
              ],
            ],
          ],
          'having' => [],
        ],
        'expires_date' => NULL,
        'description' => NULL,
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Presentation_Detail_SearchDisplay_Presentation_Detail_List_1',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Presentation_Detail_List_1',
        'label' => 'Presentation Detail List 1',
        'saved_search_id.name' => 'Presentation_Detail',
        'type' => 'list',
        'settings' => [
          'style' => 'ul',
          'limit' => '50',
          'sort' => [],
          'pager' => [],
          'columns' => [
            [
              'type' => 'field',
              'key' => 'topic_id:label',
              'dataType' => 'Integer',
              'label' => 'Topic:',
            ],
            [
              'type' => 'field',
              'key' => 'title',
              'dataType' => 'String',
              'break' => TRUE,
              'label' => 'Title:',
            ],
            [
              'type' => 'field',
              'key' => 'GROUP_CONCAT_Presentation_PresentationAuthor_Contact_01_display_name',
              'dataType' => 'String',
              'break' => TRUE,
              'label' => 'Presentation Author(s):',
              'link' => [
                'path' => '',
                'entity' => 'Contact',
                'action' => 'view',
                'join' => 'Presentation_PresentationAuthor_Contact_01',
                'target' => '_blank',
              ],
              'title' => 'View Presentation Contacts',
            ],
            [
              'type' => 'field',
              'key' => 'GROUP_CONCAT_Presentation_PresentationAuthor_Contact_01_job_title',
              'dataType' => 'String',
              'break' => TRUE,
              'label' => 'Author(s) Title(s):',
            ],
            [
              'type' => 'field',
              'key' => 'GROUP_CONCAT_Presentation_PresentationAuthor_Contact_01_Contact_Email_contact_id_01_email',
              'dataType' => 'String',
              'break' => TRUE,
              'label' => 'Author(s) Email(s):',
            ],
            [
              'type' => 'field',
              'key' => 'date',
              'dataType' => 'Date',
              'break' => TRUE,
              'label' => 'Date of original presentation:',
            ],
            [
              'type' => 'field',
              'key' => 'audience_id:label',
              'dataType' => 'Integer',
              'break' => TRUE,
              'label' => 'Audience:',
            ],
            [
              'type' => 'field',
              'key' => 'type_id:label',
              'dataType' => 'Integer',
              'break' => TRUE,
              'label' => 'Type:',
            ],
            [
              'type' => 'field',
              'key' => 'duration',
              'dataType' => 'Integer',
              'break' => TRUE,
              'rewrite' => '[duration] minutes',
              'label' => 'Duration:',
            ],
            [
              'type' => 'field',
              'key' => 'notes',
              'dataType' => 'Text',
              'break' => TRUE,
              'label' => 'Notes:',
              'rewrite' => '',
            ],
            [
              'type' => 'field',
              'key' => 'Presentation_custom.Presentation_file',
              'dataType' => 'Integer',
              'break' => TRUE,
              'label' => NULL,
              'link' => [
                'path' => '[Presentation_custom.Presentation_file]',
                'entity' => '',
                'action' => '',
                'join' => '',
                'target' => '',
              ],
              'rewrite' => 'Download this presentation',
              'icons' => [
                [
                  'icon' => 'fa-download',
                  'side' => 'left',
                  'if' => [],
                ],
              ],
            ],
          ],
          'placeholder' => 5,
          'symbol' => 'none',
        ],
        'acl_bypass' => FALSE,
      ],
    ],
  ],
];
