-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_presentation`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_presentation
-- *
-- * Presentation Custom Entity
-- *
-- *******************************************************/
CREATE TABLE `civicrm_presentation` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Presentation ID',
  `topic_id` int unsigned COMMENT 'Topic of presentation',
  `title` varchar(255) COMMENT 'Title of presentation',
  `date` date COMMENT 'Date of original presentation',
  `audience_id` int unsigned COMMENT 'Target audience of original presentation',
  `type_id` int unsigned COMMENT 'Format of original presentation',
  `duration` int COMMENT 'Length of original presentation in minutes',
  `notes` longtext COMMENT 'Additional Notes',
  `file` blob COMMENT 'Presentation file',
  PRIMARY KEY (`id`),
  INDEX `index_topic_id`(topic_id),
  INDEX `index_title`(title),
  INDEX `index_date`(date),
  INDEX `index_audience_id`(audience_id),
  INDEX `index_type_id`(type_id)
)
ENGINE=InnoDB;
